"""
Tor Hidden Service Manager.

Manages the Tor process that exposes FastAPI + Next.js as .onion addresses.

Tor config: .tor/torrc
Hidden service dir: .tor/hidden_service/
Onion address: .tor/hidden_service/hostname  (auto-generated by Tor on first start)

Ports exposed:
    .onion:80   → localhost:8000  (FastAPI)
    .onion:3000 → localhost:3000  (Next.js dashboard)

iPhone connects via Orbot (iOS Tor proxy) → SOCKS5 9050 → .onion address.
Priority: LAN direct > Tailscale > .onion (slowest, max privacy)
"""
import asyncio
import subprocess
import tempfile
import time
from pathlib import Path
from typing import Optional

from observability.logger import log

_PROJECT_ROOT = Path(__file__).parent.parent
_TORRC = _PROJECT_ROOT / ".tor" / "torrc"
_HOSTNAME_FILE = _PROJECT_ROOT / ".tor" / "hidden_service" / "hostname"
_TOR_LOG = _PROJECT_ROOT / ".tor" / "tor.log"
_TOR_BIN = "/opt/homebrew/opt/tor/bin/tor"   # Mac. Windows: C:\Tor\tor.exe

_process: Optional[subprocess.Popen] = None
_onion_address: Optional[str] = None


def get_onion_address() -> Optional[str]:
    """Read the .onion address from the hostname file."""
    global _onion_address
    if _onion_address:
        return _onion_address
    if _HOSTNAME_FILE.exists():
        addr = _HOSTNAME_FILE.read_text().strip()
        if addr:
            _onion_address = addr
            return _onion_address
    return None


def is_running() -> bool:
    global _process
    if _process is None:
        return False
    return _process.poll() is None


async def start() -> dict:
    """Start the Tor hidden service process."""
    global _process

    if is_running():
        onion = get_onion_address()
        return {"ok": True, "already_running": True, "onion": onion}

    if not Path(_TOR_BIN).exists():
        return {"ok": False, "error": f"Tor binary not found at {_TOR_BIN}. Run: brew install tor"}

    if not _TORRC.exists():
        return {"ok": False, "error": "torrc not found. Run setup first."}

    _stderr_file = open(_TOR_LOG.with_suffix(".stderr"), "w")
    try:
        _process = subprocess.Popen(
            [_TOR_BIN, "-f", str(_TORRC)],
            stdout=subprocess.DEVNULL,
            stderr=_stderr_file,
        )
        log.info("tor_starting", pid=_process.pid)

        # Wait up to 15s for .onion address to be generated
        for _ in range(30):
            await asyncio.sleep(0.5)
            if _HOSTNAME_FILE.exists() and _HOSTNAME_FILE.stat().st_size > 0:
                break

        if _process.poll() is not None:
            # Process exited early — read stderr for diagnosis
            _stderr_file.flush()
            stderr_content = _TOR_LOG.with_suffix(".stderr").read_text()[-500:]
            log.error("tor_exited_early", returncode=_process.returncode, stderr=stderr_content)
            return {"ok": False, "error": f"Tor exited (code {_process.returncode})", "stderr": stderr_content}

        onion = get_onion_address()
        if onion:
            log.info("tor_started", onion=onion, pid=_process.pid)
            return {"ok": True, "onion": onion, "pid": _process.pid}
        else:
            return {"ok": True, "onion": None,
                    "message": "Tor starting — .onion address pending circuit bootstrap"}

    except Exception as e:
        log.error("tor_start_failed", error=str(e))
        return {"ok": False, "error": str(e)}
    finally:
        _stderr_file.close()


def stop() -> dict:
    """Stop the Tor process."""
    global _process
    if _process and _process.poll() is None:
        _process.terminate()
        _process.wait(timeout=5)
        log.info("tor_stopped")
        _process = None
        return {"ok": True}
    return {"ok": True, "message": "Tor was not running"}


def status() -> dict:
    running = is_running()
    onion = get_onion_address()
    return {
        "running": running,
        "onion_address": onion,
        "api_url": f"http://{onion}" if onion else None,
        "dashboard_url": f"http://{onion}:3000" if onion else None,
        "socks_proxy": "127.0.0.1:9050",
        "torrc": str(_TORRC),
        "pid": _process.pid if running and _process else None,
    }
